AllCops:
  UseCache: false
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
